build:
    maturin build --release

# https://test.pypi.org/manage/account/token/
test-upload:
    maturin upload --repository testpypi target/wheels/*.whl

test-install:
    pip install -i https://test.pypi.org/simple/ code-splitter

upload:
    maturin upload target/wheels/*.whl

install:
    pip install code-splitter
